### ISSUE TITLE
Setup second network interface when uTCA

### ISSUE THREAD

**Issue by hinxx** [icshwi/essdm_scripts#3]
This internal NIC connects to MCH switch, so that MCH console can be accessed through telnet:

`[ess-dev@localhost ~]$ ifconfig enp8s0f0 192.168.1.40 up
`

**Comment by jeonghanlee** [comment]
The function is implemented at 374f98f9f3699e3020114dbc66d4b9dfb1789fb3 , but I didn't test it. Anyway, I can setup it once by hand easily before we deploys any system to you. I think, it is the cost-effective solution which we can have right now.

**Comment by hinxx** [comment]
I experienced quite strange behavior in the last couple days when trying to connect to MCH.
Locally, from MTCA CPU, I would do the telnet to 192.168.1.41 as usual. It worked, but I was connecting to the MCH on another MTCA crate ?!?! I could tell by looking at the list of FRUs and it did not match what I had in the crate.. Interestingly on one occasion I saw ICS1410 among the lusted FRUs .. LOL


I think we need to stop doing CPU to MCH connections through local 192.168.1.x subnet because something is not right..

The solution would be to have MCH get IP from the DHCP server in a same way that CPU does. This way one can access MCH over the network even if the CPU is not power/present.

What do you think?

**Comment by jeonghanlee** [comment]
You saw the secret place ...LOL.  Let's discuss this soon after the first demo system of the 1410 system. :)

**Comment by jeonghanlee** [comment]
closed this repo
